name: ğŸ“¦Create Pre-Release

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    name: ğŸ—ï¸ Build package and publish to pypi
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/canaryml
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'develop'
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ğŸSetup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: ğŸ§™â€â™‚ï¸Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: ğŸ”¨Install dependencies
        run: uv sync --all-extras --dev
      - name: â¬‡ï¸ Download current coverage report
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report-${{github.event.pull_request.number}}
          path: ./coverage.xml
      - name: ğŸ“ƒPytest coverage report
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-xml-coverage-path: ./coverage.xml

      - name: âœï¸ Update Readme with Coverage Badge
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

      - name: ğŸš€ Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: "prerelease"
          root_options: "-c config/.python-semantic-release.json"

      - name: ğŸ Publish package distributions to PyPI
        if: steps.release.outputs.released == 'true'
        run: uv publish

      - name: ğŸ™ Publish package distributions to GitHub Releases
        uses: python-semantic-release/publish-action@9
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
